export const supplierCodes = [
  { code: 'ADT', name: 'Fidelity ADT' },
  { code: 'ADTLBC', name: 'ADT FEDELITY LBC' },
  { code: 'B/WEST', name: 'Beaufort West Municipality' },
  { code: 'BLACK', name: 'Blacklist Security Services (Pty) Ltd' },
  { code: 'BLIND', name: 'BLIND GUYS' },
  { code: 'BREDE', name: 'Breedevalley Municipality' },
  { code: 'BREDEN', name: 'Bredenet Herotel (Pty) Ltd' },
  { code: 'BURROU', name: 'Burrough Place (Vexti Ply Ltd)' },
  { code: 'CAPE00', name: 'CAPE AGULHAS MUNICIPALITY' },
  { code: 'CART', name: 'Cartrack Pty Ltd' },
  { code: 'CERA01', name: 'Ceres Alarms' },
  { code: 'CLAN', name: 'CLANWILLIAM COUNTRY HOTEL' },
  { code: 'CLOUD', name: 'Cloud Connect Pty Ltd' },
  { code: 'CPOMP1', name: 'Computer Mania' },
  { code: 'CYB001', name: 'Cybersmart' },
  { code: 'DIEANK', name: 'DIE ANKER ACCOMMODATION PTY' },
  { code: 'ESKOM1', name: 'Eskom Holdings' },
  { code: 'GEORGE', name: 'George Municipality' },
  { code: 'GEOTH', name: 'George Municipality - Thembalethu' },
  { code: 'GOLDEN', name: 'GOLDEN KEY GUESTHOUSE' },
  { code: 'HESHEI', name: 'Hessequa Municipality - Heidelberg' },
  { code: 'HESMEL', name: 'Hessequa Municipality - Melkhoutfontein' },
  { code: 'HESRIV', name: 'Hessequa Municipality - Riversdale' },
  { code: 'HESSIQ', name: 'Hessequa Municipality' },
  { code: 'HESSLA', name: 'Hessequa Municipality - Slangivier' },
  { code: 'ICDLSA', name: 'ICDL OF SOUTH AFRICA' },
  { code: 'JHRTF', name: 'JH Relief' },
  { code: 'KANNA', name: 'KANNALAND MUNICIPALITY' },
  { code: 'LAHMON', name: 'Lah Moniqque Food Services' },
  { code: 'LANG01', name: 'Langeberg Municipality' },
  { code: 'MATBIT', name: 'Matzikama Municipality - Bitterfontein' },
  { code: 'MATKLA', name: 'Matzikama municipality - Klawer' },
  { code: 'MATRIE', name: 'Matzikama Municipality - RIETPOORT' },
  { code: 'MATVAN', name: 'Matzikama Municipality - Vanrhynsdorp' },
  { code: 'MATVRE', name: 'Matzikama Municipality - Vredendal' },
  { code: 'MATZDO', name: 'Matzikama Municipality - Doringbaai' },
  { code: 'MATZI', name: 'MATZIKAMA MUNICIPALITY' },
  { code: 'MDW001', name: 'MD Wireless' },
  { code: 'MOSBAY', name: 'Mossel Bay Municipality' },
  { code: 'MUS001', name: 'Mustek Limited' },
  { code: 'NAS001', name: 'Nashua Cape Town' },
  { code: 'OFNATI', name: 'Office National' },
  { code: 'OUDTSH', name: 'OUDTSHOORN INN HOTEL' },
  { code: 'PAAC', name: 'Prince Albert Advice Centre' },
  { code: 'PAP001', name: 'PAPER BOSS' },
  { code: 'PHILVG', name: 'Philippi Village' },
  { code: 'POST', name: 'POSTNET OUDTSHOORN' },
  { code: 'POSTNE', name: 'Postnet Capetown' },
  { code: 'PRINCE', name: 'PRINCE ALBERT WIRELESS' },
  { code: 'RIEBEN', name: 'Riebens Computers' },
  { code: 'ROCK', name: 'THE ROCKFELLER HOTEL' },
  { code: 'SEC005', name: 'Section Five' },
  { code: 'SIMPL', name: 'Simple Pay' },
  { code: 'SNOWBA', name: 'Snowball Herotel (Pty)' },
  { code: 'SNOWKL', name: 'SNOWBALL KLAPMUTS' },
  { code: 'STO001', name: 'Stor-Age Oudtshoorn' },
  { code: 'SWELL', name: 'Swellendam Municipality' },
  { code: 'SWRT', name: 'Swartland Municipality' },
  { code: 'TCS', name: 'The Computer Shop' },
  { code: 'TELKOM', name: 'Telkom LBC' },
  { code: 'TELMER', name: 'Telkom Rental - Merweville' },
  { code: 'THEE01', name: 'Theewaterskloof Municipality' },
  { code: 'TOWER', name: 'TOWERZICHT GUEST HOUSE' },
  { code: 'TRSPAT', name: 'Trust Patrol' },
  { code: 'TRUSC', name: 'Trusc Pty ltd' },
  { code: 'TZAB01', name: 'Tzab IT Solutions' },
  { code: 'VOORSO', name: 'VOORSORG GASTEHUIS' },
  { code: 'WAL001', name: 'Waltons Vredenburg' },
  { code: 'WISHEI', name: 'Wispernet Heidelberg' },
  { code: 'WISMEL', name: 'Wispernet Melkhoutfontein' },
  { code: 'WISP4', name: 'Wispernet Dysselsdorp' },
  { code: 'WISPEN', name: 'Wispernet Internet Srvices' },
  { code: 'WISPER', name: 'Wispernet Bridgton' },
];
